ktor:
    application:
        modules:
            - com.zioanacleto.ApplicationKt.module
    deployment:
        port: 9292
        maxInitialLineLength: 2048
        maxHeaderSize: 1024
        maxChunkSize: 42
